### ISSUE TITLE
peerDependancy error with nodejs4

### ISSUE THREAD

**Issue by jackmitch** [imyller/meta-nodejs-contrib#3]
Hi,

I am hitting an issue building bower, one of the dependencies is failing due to npm not correctly parsing the rc1 version of grunt. Please see attached debug log.

I'm not sure how to hack around this in OE, any ideas?

[npm-debug.txt](https://github.com/imyller/meta-nodejs-contrib/files/409330/npm-debug.txt)

**Comment by mdavis777** [comment]
It appears to be an upstream bower, npm issue.  I got a patch that should get you going just add it to your bower recipe though the normal [openembedded patch method](http://docs.openembedded.ru/src_uri_variable.html).  I did a simple test and it works, but I don't have the time to do full tests to make sure it works perfectly in all scenarios.
Otherwise you can use npm 6.x which does not have this issue.

[grunt-fix.txt](https://github.com/imyller/meta-nodejs-contrib/files/409472/grunt-fix.txt)

**Comment by imyller** [comment]
@mdavis777 Do you feel that this patch should be applied in our layer or is this soon going away in future bower releases?

**Comment by mdavis777** [comment]
A quick look at the bower repository shows it is already fixed there.  No clue when the next bower release is planned, but it will be fixed there.
I don't see any harm with adding it to our layer and taking it out once we get a new bower.  I just need to test it with 0.x and 6.x npm and make sure I didn't break something by chance.

**Comment by imyller** [comment]
Sounds good 👍 Feel free to commit in master. I'll merge to release branches as usual.

**Comment by mdavis777** [comment]
Everything tested out good.  Pushing to master and closing issue.
